### ISSUE TITLE
About the final Warped image

### ISSUE THREAD

**Issue by TVayne** [wanghaostu/ULAE-net#1]
hi @wanghaostu  
我阅读您的代码之后发现，在代码中最终得到的配准结果是由Φ3 warped得到的，而不是由Φ1，Φ2，Φ3综合计算得到的Φ来warped的。但是我按照这样训练之后效果还不错。另外您是否有测试过平滑性呢？期望能够得到您的回复。谢谢

**Comment by wanghaostu** [comment]
In ULAE forward:
`    def forward(self, x, y):
        flow1, warp1, _= self.acc1(x, y)
        flow2, warp2, _ = self.acc2(warp1, y)
        flow3, warp3, _ = self.acc3(warp2, y)

        flowa = flow1
        flowb = self.transformer(flowa, flow2) + flow2
        flowc = self.transformer(flowb, flow3) + flow3

        return [warp1, warp2, warp3], [flowa, flowb, flowc], [flow1, flow2, flow3]`

In training:
`warps, flows, _ = model(X, Y)\`
这里的flows[-1] 就是 flowc  是flow1 flow2 flow3 三个的累积

在本方法中并没有针对平滑性的约束，在mindboggle101上的实验结果为  
  雅克比为负数占非背景比率 (标准差)  0.0453 (0.0035)
略弱于其他方法。

**Comment by tzp123456** [comment]
hi @wanghaostu 
感谢您的回复。
> 这里的flows[-1] 就是 flowc 是flow1 flow2 flow3 三个的累积
这里没问题。
` warps, flows, _ = model(X, Y)
  sim_loss_1, sim_loss_2, sim_loss_3 = sim_loss_fn(warps[2], Y)`
我的意思是这里的warps[2]，是由flow3变形得到的，而我们需要的是由flowc变形得到的图像，对吧？
谢谢您，祝好！

**Comment by TVayne** [comment]
hi @wanghaostu 
感谢您的回复。
这里的flows[-1]_ 就是 flowc 是flow1 flow2 flow3 三个的累积。这里没问题
In training:
`            warps, flows, _ = model(X, Y)
            sim_loss_1, sim_loss_2, sim_loss_3 = sim_loss_fn(warps[2], Y)`
我的意思是这里的warps[2]，是由flow3变形得到的warped3，而我们需要的是由flowc变形得到的图像，对吧？
祝好！

**Comment by wanghaostu** [comment]
是的，flow3是 warps[1] 到 warps[2]的形变场，而flowc是moving到 warps[2]的形变场。
